spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://compass.cl4r8ekukr0f.ap-northeast-2.rds.amazonaws.com:3306/compass
    username: admin
    password: compass##1101$$
  mail:
    host: smtp.gmail.com
    port: 587
    username: mini011029@gmail.com
    password: xlnrvyoantfyaxkw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            clientSecret: Y0d1l8Df2q

jwt:
  secret: VnQRc+GlyN7G6rY31mDIRUC0zFo7TVPpIwAoon8cx9Gjj5UgAVjGo/js24LstR8ZByH36a08Ng6EJeGUQs7rcQ==